### ISSUE TITLE
PERIOD_CODE not working

### ISSUE THREAD

**Issue by pkamphuis** [jirikostiha/xtb-xApi#10]
public static readonly PERIOD_CODE PERIOD_H1 = new(PERIOD_H1_CODE);

is never initialised correctly, code is always 0

**Comment by pkamphuis** [comment]
Is due to an error in the BaseCode constructor

**Comment by jirikostiha** [comment]
I found it also and fixed it in main branch few commits ago. Probably because of merge in past.
