### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pkamphuis** [jirikostiha/xtb-xApi#2]
Hi Jiri,

Nice work on updating this library. I was about to update my copy. But I might take this one.
What additional changes have you in mind? Is there anything I can do to help?

I would start with disabling CS1573
and fixing CA1309 and CA1852
Just to clean up the list of warnings

Best regards,

Paul

**Comment by jirikostiha** [comment]
Hi Paul,

that is great it is interesting for you;)
I just published last important change (async methods) and I dont have more to add at least at this time. If you want to solve warnings or something else, dont hesitate to do it, it would be perfect. 
My idea is keep this project similar to original one with additive changes "only" if possible. In case if xtb will release newer version a merge would be easy. But on the other hand it is not likely they release new version or version based on this v2.5.0.

Regards
Jiri

**Comment by jirikostiha** [comment]
closed
